name: Ci

on:
  push:
    branches:
    - main
    - ci
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        sudo apt update
        sudo -EDEBIAN_FRONTEND apt install -y --no-install-recommends wabt
      env:
        DEBIAN_FRONTEND: noninteractive
    - uses: actions/setup-node@v2
      with:
        node-version: 16.x
    - run: |
        npm install
        npm run build
        npm run test -- --coverage
    - uses: codecov/codecov-action@v2
      with:
        files: coverage/lcov.info
